spring:
  cloud:
    stream:
      bindings:
        temporalEvents:
          binder: rabbit

---
spring:
  profiles: local
  rabbit:
    host: localhost
    port: 5672
    username: 5672
    password: 5672

---
spring:
  profiles: cloud